#This object stores everything generated by the agents
from typing import TypedDict


class PaperState(TypedDict):
    paper_text: str

    analysis: str
    summary: str
    citations: str
    insights: str

    review_score: int
    retries: int

    final_report: str